### ISSUE TITLE
Suggestions and improvements

### ISSUE THREAD

**Issue by LeuAlmeida** [tatishinoda/portfolio2020#2]
Tati,

Follow my considerations about your code and folder structure.

### Folders and files structure
First of all, I think that `header/Header.js` may be `src/components/Header/index.js` as well as `home/Home.js`should be `Home/index.js`. Semantically it is the same that to say "it is a component".

### Code structure
https://github.com/tatishinoda/portfolio2020/blob/4bc59081e3adba850666ae67d272889dfa2bf8c9/src/components/header/Header.js#L34
The Header component has a **Home** import. It is a little confuse, considering that is the Header component. 
I think that it may be better if the `<Home />` if he be instantiated in the `App.js` file. What do you think?

**Comment by tatishinoda** [comment]
Thank you Léu!
I already fixed the folder and file structure on my new commit. 
Also, I've modified the import on Header.
